import { createHash } from 'node:crypto';
import { mkdir, readFile, unlink, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

import { LOCALES, PAGES, ROUTES, SITE } from '../site/content.mjs';
import { renderPage } from '../site/render.mjs';

const projectRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const publicRoot = path.join(projectRoot, 'public');
const checkOnly = process.argv.includes('--check');
const pageTypes = Object.keys(ROUTES);
const localeKeys = Object.keys(LOCALES);
const assetVersion = SITE.assetVersion;

function outputPath(pathname) {
    if (pathname === '/') return path.join(publicRoot, 'index.html');
    return path.join(publicRoot, pathname.replace(/^\//u, ''), 'index.html');
}

function xmlEscape(value) {
    return String(value)
        .replaceAll('&', '&amp;')
        .replaceAll('<', '&lt;')
        .replaceAll('>', '&gt;')
        .replaceAll('"', '&quot;')
        .replaceAll("'", '&apos;');
}

function buildSitemap() {
    const entries = [];
    for (const pageType of pageTypes) {
        for (const localeKey of localeKeys) {
            const pathname = ROUTES[pageType][localeKey];
            const alternates = localeKeys.map((key) => `    <xhtml:link rel="alternate" hreflang="${LOCALES[key].hreflang}" href="${xmlEscape(`${SITE.domain}${ROUTES[pageType][key]}`)}"/>`).join('\n');
            entries.push(`  <url>
    <loc>${xmlEscape(`${SITE.domain}${pathname}`)}</loc>
    <lastmod>${SITE.lastModified}</lastmod>
${alternates}
    <xhtml:link rel="alternate" hreflang="x-default" href="${xmlEscape(`${SITE.domain}${ROUTES[pageType].ru}`)}"/>
  </url>`);
        }
    }
    return `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:xhtml="http://www.w3.org/1999/xhtml">
${entries.join('\n')}
</urlset>
`;
}

function buildRedirects() {
    const lines = new Set(['/index / 301', '/index.html / 301']);
    for (const pageType of pageTypes) {
        for (const localeKey of localeKeys) {
            const canonical = ROUTES[pageType][localeKey];
            if (canonical === '/') continue;
            const withoutSlash = canonical.slice(0, -1);
            lines.add(`${withoutSlash} ${canonical} 301`);
            lines.add(`${withoutSlash}.html ${canonical} 301`);
            lines.add(`${withoutSlash}/index ${canonical} 301`);
            lines.add(`${withoutSlash}/index.html ${canonical} 301`);
        }
    }
    return `${[...lines].join('\n')}\n`;
}

function cspHash(text) {
    return `'sha256-${createHash('sha256').update(text, 'utf8').digest('base64')}'`;
}

function buildHeaders(schemaTexts) {
    const hashes = [...new Set(schemaTexts.map(cspHash))].sort().join(' ');
    const csp = [
        "default-src 'self'",
        `script-src 'self' ${hashes}`,
        "script-src-attr 'none'",
        "style-src 'self' https://fonts.googleapis.com",
        "font-src https://fonts.gstatic.com",
        "img-src 'self' data: blob:",
        "media-src 'self'",
        "connect-src 'self'",
        "object-src 'none'",
        "base-uri 'self'",
        "form-action 'self'",
        "frame-ancestors 'none'",
        'upgrade-insecure-requests'
    ].join('; ');
    if (csp.length > 2_000) throw new Error(`CSP is too long: ${csp.length} characters`);

    return `/*
  Content-Security-Policy: ${csp}
  Cross-Origin-Opener-Policy: same-origin
  Cross-Origin-Resource-Policy: same-origin
  Permissions-Policy: camera=(), geolocation=(), microphone=(), payment=(), usb=()
  Referrer-Policy: strict-origin-when-cross-origin
  Strict-Transport-Security: max-age=63072000; includeSubDomains; preload
  X-Content-Type-Options: nosniff
  X-Frame-Options: DENY

/*.html
  Cache-Control: public, max-age=0, must-revalidate

/*.css
  Cache-Control: public, max-age=3600, stale-while-revalidate=86400

/*.js
  Cache-Control: public, max-age=3600, stale-while-revalidate=86400

/assets/*
  Cache-Control: public, max-age=86400, stale-while-revalidate=604800

/sitemap.xml
  Cache-Control: public, max-age=3600

/robots.txt
  Cache-Control: public, max-age=3600

/send
  Cache-Control: no-store

/health
  Cache-Control: no-store
  X-Robots-Tag: noindex, nofollow

https://:version.:subdomain.workers.dev/*
  X-Robots-Tag: noindex, nofollow
`;
}

function buildRobots() {
    return `User-agent: *
Allow: /
Disallow: /send
Disallow: /health

Sitemap: ${SITE.domain}/sitemap.xml
`;
}

function buildClientLocales() {
    const clientLocales = Object.fromEntries(localeKeys.map((localeKey) => [localeKey, {
        intlLocale: LOCALES[localeKey].intlLocale,
        calculator: LOCALES[localeKey].calculator
    }]));
    return `// Generated by scripts/build-site.mjs. Edit site/content.mjs instead.\nexport const CLIENT_LOCALES = Object.freeze(${JSON.stringify(clientLocales)});\n`;
}

function build404() {
    return `<!DOCTYPE html>
<html lang="mul">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="robots" content="noindex, nofollow">
    <meta name="theme-color" content="#010409">
    <title>404 | AsiaTechnoStroy</title>
    <link rel="stylesheet" href="/style.css?v=${assetVersion}">
    <link rel="icon" href="/favicon.ico" sizes="any">
</head>
<body class="not-found-page">
    <main class="not-found" id="main-content">
        <div class="not-found__code">404</div>
        <p class="eyebrow">ASIATECHNOSTROY</p>
        <h1>Page not found</h1>
        <p lang="ru">Страница не найдена. Выберите язык, чтобы вернуться на сайт.</p>
        <p lang="uz">Sahifa topilmadi. Saytga qaytish uchun tilni tanlang.</p>
        <p lang="en">The page could not be found. Select a language to return to the site.</p>
        <div class="not-found__actions">
            <a class="btn-premium" href="/">Русский</a>
            <a class="hero-secondary" href="/uz/">O‘zbekcha</a>
            <a class="hero-secondary" href="/en/">English</a>
        </div>
    </main>
</body>
</html>
`;
}

function validatePage(html, localeKey, pageType) {
    const canonical = `${SITE.domain}${ROUTES[pageType][localeKey]}`;
    const h1Count = (html.match(/<h1(?:\s|>)/gu) || []).length;
    if (h1Count !== 1) throw new Error(`${localeKey}/${pageType}: expected one H1, found ${h1Count}`);
    if (!html.includes(`<html lang="${LOCALES[localeKey].htmlLang}">`)) throw new Error(`${localeKey}/${pageType}: wrong lang`);
    if (!html.includes(`<link rel="canonical" href="${canonical}">`)) throw new Error(`${localeKey}/${pageType}: wrong canonical`);
    for (const key of localeKeys) {
        const expected = `<link rel="alternate" hreflang="${LOCALES[key].hreflang}" href="${SITE.domain}${ROUTES[pageType][key]}">`;
        if (!html.includes(expected)) throw new Error(`${localeKey}/${pageType}: missing ${key} alternate`);
    }
    if (/\s(?:onclick|onload|onerror)=/iu.test(html)) throw new Error(`${localeKey}/${pageType}: inline handler found`);
    if (/\sstyle=/iu.test(html)) throw new Error(`${localeKey}/${pageType}: inline style found`);
    const ids = [...html.matchAll(/\sid="([^"]+)"/gu)].map((match) => match[1]);
    if (new Set(ids).size !== ids.length) throw new Error(`${localeKey}/${pageType}: duplicate id found`);
    for (const [, fragment] of html.matchAll(/href="#([^"]+)"/gu)) {
        if (!ids.includes(fragment)) throw new Error(`${localeKey}/${pageType}: missing fragment target #${fragment}`);
    }
    const schemaMatch = html.match(/<script type="application\/ld\+json">([\s\S]*?)<\/script>/u);
    if (!schemaMatch) throw new Error(`${localeKey}/${pageType}: JSON-LD missing`);
    JSON.parse(schemaMatch[1]);
}

function expectedFiles() {
    const files = new Map();
    const schemaTexts = [];
    for (const pageType of pageTypes) {
        for (const localeKey of localeKeys) {
            if (!PAGES[localeKey]?.[pageType]) throw new Error(`Missing page content: ${localeKey}/${pageType}`);
            const { html, schemaText } = renderPage(localeKey, pageType);
            validatePage(html, localeKey, pageType);
            files.set(outputPath(ROUTES[pageType][localeKey]), html);
            schemaTexts.push(schemaText);
        }
    }
    files.set(path.join(publicRoot, 'sitemap.xml'), buildSitemap());
    files.set(path.join(publicRoot, 'robots.txt'), buildRobots());
    files.set(path.join(publicRoot, 'i18n.js'), buildClientLocales());
    files.set(path.join(publicRoot, '_redirects'), buildRedirects());
    files.set(path.join(publicRoot, '_headers'), buildHeaders(schemaTexts));
    files.set(path.join(publicRoot, '404.html'), build404());
    return files;
}

async function previousGeneratedPages() {
    const sitemap = await readFile(path.join(publicRoot, 'sitemap.xml'), 'utf8').catch(() => null);
    if (!sitemap) return new Map();

    const siteOrigin = new URL(SITE.domain).origin;
    const pages = new Map();
    for (const match of sitemap.matchAll(/<loc>(.*?)<\/loc>/gu)) {
        let url;
        try {
            url = new URL(match[1]);
        } catch {
            continue;
        }
        if (url.origin !== siteOrigin || url.search || url.hash || !url.pathname.endsWith('/')) continue;

        const filename = outputPath(url.pathname);
        const relative = path.relative(publicRoot, filename);
        if (relative.startsWith('..') || path.isAbsolute(relative)) continue;
        pages.set(filename, url.href);
    }
    return pages;
}

async function isGeneratedPage(filename, canonical) {
    const html = await readFile(filename, 'utf8').catch(() => null);
    return html?.includes(`<link rel="canonical" href="${canonical}">`) ?? false;
}

async function run() {
    // The previous generated sitemap acts as a route manifest. This lets us remove
    // only pages that this generator previously owned, without touching assets or
    // unrelated HTML that a user may have placed in public/.
    const previousPages = await previousGeneratedPages();
    const files = expectedFiles();
    const expectedPages = new Set(pageTypes.flatMap((pageType) =>
        localeKeys.map((localeKey) => outputPath(ROUTES[pageType][localeKey]))
    ));
    const stale = [];

    for (const [filename, canonical] of previousPages) {
        if (expectedPages.has(filename) || !(await isGeneratedPage(filename, canonical))) continue;
        if (checkOnly) {
            stale.push(path.relative(projectRoot, filename));
        } else {
            await unlink(filename);
        }
    }

    for (const [filename, content] of files) {
        if (checkOnly) {
            const existing = await readFile(filename, 'utf8').catch(() => null);
            if (existing !== content) stale.push(path.relative(projectRoot, filename));
            continue;
        }
        await mkdir(path.dirname(filename), { recursive: true });
        await writeFile(filename, content, 'utf8');
    }
    if (stale.length) throw new Error(`Generated site is stale:\n${stale.join('\n')}`);
    const mode = checkOnly ? 'verified' : 'generated';
    console.log(`Site ${mode}: ${pageTypes.length * localeKeys.length} pages, ${files.size} output files.`);
}

await run();
